### ISSUE TITLE
Cadastro de usuário

### ISSUE THREAD

**Issue by guibrbs** [guibrbs/To-Do-List#2]
# Descrição
Usuário ser capaz de se registrar no aplicativo utilizando um nome, e-mail e senha.

# Tasks
- [x] Criação de tela de registro com form com campos email, nome e senha;
- [x] Criação de método que envia dados para firebase;
- [x] Conexão da tela de registro com metódos;
- [x] Criação de método que guarda os dados no firestore;
